config/routes.rb
Rails.application.routes.draw do

  get "/signup", to: "users#new"

  post "/signup", to: "users#create"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    root "static_pages#home"
    resources :books
    resources :users, only: [:index, :destroy]
    resources :categories, except: :show
    resources :requests, only: [:update, :edit, :index]
  end

  resources :users, except: [:edit, :update, :destroy]
  resources :books, only: [:index, :show]
  resources :requests, except: [:show, :update, :edit]
  resources :user_books, only: [:create, :update]
  resources :reviews, except: :index
  resources :likes, only: [:create, :destroy]
  root "static_pages#home"

  resources :relationships, only: [:create, :destroy, :index]
end

app/views/layouts/admin/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("header.logo"), admin_root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("header.home"), admin_root_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("header.books"), admin_books_path %></li>
          <li><%= link_to t("header.users"), admin_users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("login.profile"), "#" %></li>
              <li><%= link_to t("login.setting"), "#" %></li>
              <li>
                <%= link_to t("login.logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("login.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield :title %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", media: "all",
    "data-turbolinks-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
</head>

<body>
  <%= render "layouts/admin/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>