config/routes.rb
Rails.application.routes.draw do

  get "/signup", to: "users#new"

  post "/signup", to: "users#create"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    root "static_pages#home"
    resources :books
    resources :users, only: [:index, :destroy]
    resources :categories, except: :show
    resources :requests, only: [:update, :edit, :index]
  end

  resources :users, except: [:edit, :update, :destroy]
  resources :books, only: [:index, :show]
  resources :requests, except: [:show, :update, :edit]
  resources :user_books, only: [:create, :update]
  resources :reviews, except: :index
  resources :likes, only: [:create, :destroy]
  root "static_pages#home"

  resources :relationships, only: [:create, :destroy, :index]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "message.error " %> <%= pluralize object.errors.count,
        t("message.name_error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<div id="feed">
  <% if @feed_items.any? %>
    <ol class="activities">
      <%= render @feed_items %>
    </ol>
    <div class="row text-center">
      <%= will_paginate @feed_items %>
    </div>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <% Settings.relation.each do |key, relation| %>
    <%= link_to relationships_path user_id: @user, action_type: relation do %>
      <div class="hvr-glow col-md-5">
        <strong id=<%= relation %> class="stat">
          <%= @user.send(relation).count %>
        </strong>
        <p><%= t relation %></p>
      </div>
    <% end %>
  <% end %>
</div>