config/routes.rb
Rails.application.routes.draw do

  get "/signup", to: "users#new"

  post "/signup", to: "users#create"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    root "static_pages#home"
    resources :books
    resources :users, only: [:index, :destroy]
    resources :categories, except: :show
    resources :requests, only: [:update, :edit, :index]
  end

  resources :users, except: [:edit, :update, :destroy]
  resources :books, only: [:index, :show]
  resources :requests, except: [:show, :update, :edit]
  resources :user_books, only: [:create, :update]
  resources :reviews, except: :index
  resources :likes, only: [:create, :destroy]
  root "static_pages#home"

  resources :relationships, only: [:create, :destroy, :index]
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :author, presence: true
  validates :publish_date, presence: true
  validate :validates_publish_date_compare_now

  enum req_status: [:pendding, :accept, :reject]

  scope :order_by_time, -> {order created_at: :desc}

  private
  def validates_publish_date_compare_now
    errors.add :publish_date, I18n.t("errors.publish_date") if
      publish_date.to_date > Time.now.to_date
  end
end

app/controllers/admin/requests_controller.rb
class Admin::RequestsController < Admin::BaseController
  before_action :find_request, only: [:edit, :update]
  before_action :load_status, only: :edit

  def index
    @requests = Request.order_by_time.paginate page: params[:page],
      per_page: Settings.size
  end

  def edit
  end

  def update
    if @request.update_attributes request_params
      flash[:success] = t "flash.handle_request_success"
      redirect_to admin_requests_path
    else
      load_status
      render :edit
    end
  end

  private
  def request_params
    params.require(:request).permit :req_status
  end

  def find_request
    @request = Request.find_by id: params[:id]
    if @request.nil?
      flash[:danger] = t "flash.cant_find_request"
      redirect_to admin_root_path
    end
  end

  def load_status
    @request_statuses = Request.req_statuses.map{|key, value| [key, key]}
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :logged_in_user, only: [:index, :new, :create]
  before_action :find_request, only: :destroy

  def index
    @requests = Request.paginate page: params[:page], per_page: Settings.size
  end

  def new
    @request = current_user.requests.new
  end

  def create
    @request = current_user.requests.build request_params
    if @request.save
      flash[:success] = t "flash.send_request_success"
      redirect_to requests_url
    else
      render :new
    end
  end

  def destroy
    if @request.pendding?
      @request.destroy
      flash[:success] = t "flash.cancel_success"
      redirect_to requests_url
    else
      flash[:danger] = t "flash.cant_cancel_request"
      redirect_to requests_url
    end
  end

  private
  def request_params
    params.require(:request).permit :name, :author, :publish_date, :description
  end

  def find_request
    @request = Request.find_by id: params[:id]
    if @request.nil?
      flash[:danger] = t "flash.cant_find_request"
      redirect_to requests_url
    end
  end
end

app/views/requests/_request.html.erb
 <tr>
  <th><%= request.name %></th>
  <th><%= request.author %></th>
  <th><%= request.publish_date %></th>
  <th><%= request.description %></th>
  <th><%= request.req_status %></th>
  <th><%= link_to t("user.btn_cancel_request"), request, method: :delete,
    data: {confirm: t("confirm.cancel_request")}, class: "btn" %></th>
</tr>

app/views/requests/index.html.erb
<% provide :title, t("user.request") %>
<h1><%= t "user.request" %></h1>
<div class="row">
  <%= link_to t("user.btn_request"), new_request_path %>

  <div class="row requests">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= t "table.request.book_name" %></th>
          <th><%= t "table.request.author" %></th>
          <th><%= t "table.request.publish_date" %></th>
          <th><%= t "table.request.description" %></th>
          <th><%= t "table.request.request_status" %></th>
          <th><%= t "table.request.cancel" %></th>
        </tr>
      </thead>
      <tbody>
        <%= render @requests %>
      </tbody>
    </table>
  </div>

  <div class="row text-center">
    <%= will_paginate %>
  </div>
</div>

app/views/requests/new.html.erb
<% provide :title, t("user.new_request") %>
<h1><%= t "user.new_request" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @request do |f| %>
      <%= render "shared/error_messages", object: @request %>
      <%= f.label :book_name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :author %>
      <%= f.text_field :author, class: "form-control" %>

      <%= f.label :publish_date %>
      <%= f.date_field :publish_date, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.submit t("user.btn_request"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>