config/routes.rb
Rails.application.routes.draw do

  get "/signup", to: "users#new"

  post "/signup", to: "users#create"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    root "static_pages#home"
    resources :books
    resources :users, only: [:index, :destroy]
    resources :categories, except: :show
    resources :requests, only: [:update, :edit, :index]
  end

  resources :users, except: [:edit, :update, :destroy]
  resources :books, only: [:index, :show]
  resources :requests, except: [:show, :update, :edit]
  resources :user_books, only: [:create, :update]
  resources :reviews, except: :index
  resources :likes, only: [:create, :destroy]
  root "static_pages#home"

  resources :relationships, only: [:create, :destroy, :index]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :find_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.paginate page: params[:page],
      per_page: Settings.size
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "flash.add_category_success"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "flash.edit_category_success"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "flash.delete_category_success"
      redirect_to admin_categories_path
    else
      flash[:danger] = t "flash.delete_category_failed"
      redirect_to admin_categories_path
    end
  end

  private
  def find_category
    @category = Category.find_by id: params[:id]
    if @category.nil?
      flash[:danger] = t "flash.cant_find_category"
      redirect_to admin_categories_path
    end
  end

  def category_params
    params.require(:category).permit :name, :description
  end
end

app/views/admin/categories/_category.html.erb
<div class="text-center">
  <h3><%= category.name %></h3>
  <p><%= category.description %></p>
  <%= link_to edit_admin_category_path(category) do %>
    <span class="glyphicon glyphicon-pencil"></span>
  <% end %>
  <%= link_to [:admin, category], method: :delete,
    data: {confirm: t("confirm.delete_category")} do %>
    <span class="glyphicon glyphicon-trash text-danger"></span>
  <% end %>
</div>

app/views/admin/categories/_category_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: @category %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.submit t("btn.submit"), class: "btn btn-primary" %>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :title, t("admin_method.edit_category") %>
<h1><%= t "admin_method.edit_category" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "category_form" %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, t("categories.title") %>
<h1><%= t "categories.h1" %></h1>
<%= link_to t("admin_method.add_category"),
  new_admin_category_path, class: "btn btn-info" %>
<div class="row">
  <%= render @categories %>
</div>
<div class="row text-center">
  <%= will_paginate %>
</div>

app/views/admin/categories/new.html.erb
<% provide :title, t("admin_method.add_category") %>
<h1><%= t "admin_method.add_category" %></h1>

<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
    <%= render "category_form" %>
  </div>
</div>